name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Print environment variables  # Paso temporal para ver las variables
        run: |
          echo "REACT_APP_PHONE_FRAN=$REACT_APP_PHONE_FRAN"
          echo "REACT_APP_PHONE_LAURA=$REACT_APP_PHONE_LAURA"
        env:
          REACT_APP_PHONE_FRAN: ${{ secrets.REACT_APP_PHONE_FRAN }}
          REACT_APP_PHONE_LAURA: ${{ secrets.REACT_APP_PHONE_LAURA }}

      - name: Build project
        env:
          REACT_APP_ACCOUNT_NUMBER: ${{ secrets.REACT_APP_ACCOUNT_NUMBER }}
          REACT_APP_PHONE_FRAN: ${{ secrets.REACT_APP_PHONE_FRAN }}
          REACT_APP_PHONE_LAURA: ${{ secrets.REACT_APP_PHONE_LAURA }}
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "cristian-lidia"
          git config --global user.email "cristianlidia31052025@gmail.com"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}